/*
 * JavaAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/06/2016
 */
package com.message360.apidev;

public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://api-dev.message360.com/api/v2";

    //The username to use with basic authentication
    //TODO: Replace the basicAuthUserName with an appropriate value
    public static String basicAuthUserName = "TODO: Replace";

    //The password to use with basic authentication
    //TODO: Replace the basicAuthPassword with an appropriate value
    public static String basicAuthPassword = "TODO: Replace";

}
