/*
 * JavaAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/06/2016
 */
package com.message360.apidev;

import com.message360.apidev.controllers.*;
import com.message360.apidev.http.client.HttpClient;

public class JavaAPIClient {
    /**
     * Singleton access to Usage controller
     * @return	Returns the UsageController instance 
     */
    public UsageController getUsage() {
        return UsageController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public JavaAPIClient() {	
	}

    /**
     * Client initialization constructor 
     */     
    public JavaAPIClient(String basicAuthUserName, String basicAuthPassword) {
        this();
        Configuration.basicAuthUserName = basicAuthUserName;
        Configuration.basicAuthPassword = basicAuthPassword;
    }
}